spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jerryShop?characterEncoding=utf-8&serveTimezone=UTC
      username: root
      password: root
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.cj.jerryShop.entity